package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserGroup<M extends BaseUserGroup<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}

	public java.lang.String getUserId() {
		return get("userId");
	}

	public void setGrpId(java.lang.String grpId) {
		set("grpId", grpId);
	}

	public java.lang.String getGrpId() {
		return get("grpId");
	}

	public void setAliasName(java.lang.String aliasName) {
		set("aliasName", aliasName);
	}

	public java.lang.String getAliasName() {
		return get("aliasName");
	}

}
