package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRichMedia<M extends BaseRichMedia<M>> extends Model<M> implements IBean {

	public void setRmId(java.lang.String rmId) {
		set("rmId", rmId);
	}

	public java.lang.String getRmId() {
		return get("rmId");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}

	public java.lang.String getUserId() {
		return get("userId");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setResIds(java.lang.String resIds) {
		set("resIds", resIds);
	}

	public java.lang.String getResIds() {
		return get("resIds");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setReadNumber(java.lang.Integer readNumber) {
		set("readNumber", readNumber);
	}

	public java.lang.Integer getReadNumber() {
		return get("readNumber");
	}

	public void setDatetime(java.util.Date datetime) {
		set("datetime", datetime);
	}

	public java.util.Date getDatetime() {
		return get("datetime");
	}

}
