package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {

	public void setMenuId(java.lang.String menuId) {
		set("menuId", menuId);
	}

	public java.lang.String getMenuId() {
		return get("menuId");
	}

	public void setPId(java.lang.String pId) {
		set("pId", pId);
	}

	public java.lang.String getPId() {
		return get("pId");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setDescribe(java.lang.String Describe) {
		set("_describe", Describe);
	}

	public java.lang.String getDescribe() {
		return get("_describe");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
